coverage:
  status:
    project:
      default: false
      internal:
        target: 30%
        threshold: 10%
        paths:
        - "internal/"
    patch:
      only_pulls: true

ignore:
  - "**/mocks/*"
  - "cmd/"
  - "docs/"