%YAML 1.1
---
environment: development
log_level: DEBUG
shutdown_timeout: 10s

http_server:
  addr: :8080
  timeouts:
    read: 10s
    read_header: 10s
    write: 10s

  handlers:
    message:
      create_msg_per_minute: 1000
      get_stats_per_minute: 1000

postgres:
  migrate: true

kafka:
  client_id: "messagio-assignment"
  brokers:
    - kafka1:29092

  producers:
    messages:
      topic: "messages-to-process"

  consumers:
    processed_messages:
      group: "messagio-default"
      topics:
        - "processed-messages"
