%YAML 1.1
---
environment: production
log_level: INFO
shutdown_timeout: 10s

http_server:
  addr: 0.0.0.0:8080
  timeouts:
    read: 10s
    read_header: 10s
    write: 10s

  handlers:
    message:
      create_msg_per_minute: 50
      get_stats_per_minute: 100

postgres:
  migrate: true

kafka:
  client_id: "messagio-assignment"
  brokers:
    - kafka1:29092

  producers:
    messages:
      topic: "messages-to-process"

  consumers:
    processed_messages:
      group: "messagio-assigment"
      topics:
        - "processed-messages"